/** Demo data used when Supabase is not configured. */
export const MOCK_LOCATIONS = [
  {
    id: '1',
    name: 'Downtown Corner Spot',
    address: '123 Main St',
    city: 'Austin',
    state: 'TX',
    lat: 30.2672,
    lng: -97.7431,
    status: 'active',
    foot_traffic_score: 88,
    competition_score: 62,
    demographics_score: 75,
    accessibility_score: 90,
    rent_score: 55,
    monthly_rent: 8500,
    square_footage: 2400,
    parking_spaces: 20,
    notes: 'High foot traffic from office workers. Strong lunch potential.',
    avg_unit_volume: 1450000,
    weekly_customers: 2800,
    primary_market: 'Downtown Austin',
    created_at: '2025-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Riverside Promenade',
    address: '456 River Walk Blvd',
    city: 'Austin',
    state: 'TX',
    lat: 30.2559,
    lng: -97.7506,
    status: 'active',
    foot_traffic_score: 72,
    competition_score: 45,
    demographics_score: 83,
    accessibility_score: 68,
    rent_score: 70,
    monthly_rent: 6200,
    square_footage: 1900,
    parking_spaces: 35,
    notes: 'Great weekend traffic. Families and tourists.',
    avg_unit_volume: 980000,
    weekly_customers: 1900,
    primary_market: 'South Lamar',
    created_at: '2025-01-20T14:00:00Z',
  },
  {
    id: '3',
    name: 'East Side Hub',
    address: '789 E 6th St',
    city: 'Austin',
    state: 'TX',
    lat: 30.2595,
    lng: -97.7251,
    status: 'candidate',
    foot_traffic_score: 65,
    competition_score: 80,
    demographics_score: 71,
    accessibility_score: 60,
    rent_score: 85,
    monthly_rent: 4800,
    square_footage: 1600,
    parking_spaces: 12,
    notes: 'Emerging neighborhood, lower competition, affordable rent.',
    avg_unit_volume: 720000,
    weekly_customers: 1400,
    primary_market: 'East Austin',
    created_at: '2025-02-01T09:00:00Z',
  },
  {
    id: '4',
    name: 'South Congress Prime',
    address: '321 S Congress Ave',
    city: 'Austin',
    state: 'TX',
    lat: 30.2448,
    lng: -97.7503,
    status: 'active',
    foot_traffic_score: 95,
    competition_score: 38,
    demographics_score: 90,
    accessibility_score: 85,
    rent_score: 40,
    monthly_rent: 12000,
    square_footage: 3100,
    parking_spaces: 45,
    notes: 'Premium location on SoCo. Highest foot traffic.',
    avg_unit_volume: 1820000,
    weekly_customers: 3500,
    primary_market: 'South Congress',
    created_at: '2025-02-10T11:00:00Z',
  },
  {
    id: '5',
    name: 'North Loop Neighborhood',
    address: '654 N Loop Blvd',
    city: 'Austin',
    state: 'TX',
    lat: 30.3082,
    lng: -97.7231,
    status: 'candidate',
    foot_traffic_score: 50,
    competition_score: 90,
    demographics_score: 62,
    accessibility_score: 72,
    rent_score: 92,
    monthly_rent: 3600,
    square_footage: 1400,
    parking_spaces: 18,
    notes: 'Low competition, suburban residential area, low rent.',
    avg_unit_volume: 0,
    weekly_customers: 0,
    primary_market: 'North Austin',
    created_at: '2025-02-15T08:00:00Z',
  },
];

export const MOCK_SURVEYS = [
  {
    id: 's1',
    location_id: '1',
    respondent_name: 'Alex Johnson',
    age_group: '25-34',
    income_level: '50k_75k',
    visit_frequency: 'weekly',
    preferred_cuisine: 'American',
    location_rating: 5,
    would_visit: true,
    travel_distance: '1_3mi',
    comments: 'Love the area, great for a quick lunch.',
    created_at: '2025-02-20T12:00:00Z',
  },
  {
    id: 's2',
    location_id: '2',
    respondent_name: 'Maria Garcia',
    age_group: '35-44',
    income_level: '75k_100k',
    visit_frequency: 'monthly',
    preferred_cuisine: 'Mexican',
    location_rating: 4,
    would_visit: true,
    travel_distance: '3_5mi',
    comments: 'Nice riverside views, good parking.',
    created_at: '2025-02-21T15:00:00Z',
  },
  {
    id: 's3',
    location_id: '4',
    respondent_name: 'Sam Torres',
    age_group: '18-24',
    income_level: '30k_50k',
    visit_frequency: 'weekly',
    preferred_cuisine: 'Asian Fusion',
    location_rating: 5,
    would_visit: true,
    travel_distance: '0_1mi',
    comments: 'SoCo is always buzzing!',
    created_at: '2025-02-22T10:00:00Z',
  },
];
